Added TransactionSet
Supports mutation during iteration.  Changes made within one iterator
won't reflect until a new iterator is created on the set.  Primarily
intended to be used with the set_transaction contextmanager:

scores = set(range(5))
for score in scores:
scores.add(score**2)
RuntimeError: Set changed size during iteration

scores = set(range(5))
with set_transaction(scores) as mutable:
for score in mutable:
mutable.add(score**2)
print scores
mutable.clear()
mutable._set.clear()
print scores
# Output:
# set([0, 1, 2, 3, 4, 9, 16])
# set([0, 1, 2, 3, 4, 9, 16])

Note that the mutable variable is used within the block, but the
original set is changed once you exit the block.  The transaction set
does not keep a reference to the original set - that is handled by the
context manager.